"""empty message

Revision ID: 81cb49596c98
Revises: e3cb38237ac9
Create Date: 2023-04-08 22:55:51.858632

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "81cb49596c98"
down_revision = "e3cb38237ac9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("api_key", sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, "user", ["api_key"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "api_key")
    # ### end Alembic commands ###
